# Generated by Django 5.2 on 2025-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse', '0005_remove_civicissue_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
