# Generated by Django 5.2 on 2025-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
