# Generated by Django 5.2 on 2025-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Issue'), ('electric_line', 'Electric Line Issue'), ('plumbing', 'Plumbing Issue'), ('garbage', 'Garbage Issue'), ('drainage', 'Drainage Issue'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='other_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
