# Generated by Django 5.2 on 2025-04-26 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse', '0004_civicissue_category_civicissue_other_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civicissue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='civicissue',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='civicissue',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='civicissue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='civicissue',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='civicissue',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='issue_media/'),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='category',
            field=models.CharField(choices=[('road', 'Road'), ('electric_line', 'Electric Line'), ('plumbing', 'Plumbing'), ('garbage', 'Garbage'), ('drainage', 'Drainage'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
